### ISSUE TITLE
OpenEVSE charge current setting changing randomly

### ISSUE THREAD

**Issue by DrFrankReade** [TonyApuzzo/home-assistant-config#2]
Hello,

I'm experiencing odd behavior since a recent update of the OpenEVSE.yaml where the charge current (as by the pilot signal) will change to a different value, seemingly on its own, and is all over the place as to the value - Today it was 19 amps. My default is 40A, the change occurs at unknown times, maybe 4-5 times a week, so not every day, but I'm only noticing because I'm checking. I've turned off the `Set OpenEVSE Charge Current` automation to see if the updates still happen, which has disabled the slider, and will report, but I'm wondering if this behavior is the result of something intentional or if anybody else has experienced it.

I do not have logging to SQL enabled since a recent SD card death, presumably due to over-use, so I realize that I could probably be a lot more helpful. 

Thank you.

**Comment by TonyApuzzo** [comment]
It does seem to be a real problem but I haven't figured out where it is coming from yet. There must be _some_ reason, since I'm seeing something similar. Mine seems to reset the pilot current to 21A occasionally.

I wasn't sure if it is was something unique to me or not.  Thanks for reporting this and with more data maybe it will be easier to figure out.

**Comment by TonyApuzzo** [comment]
I caught it doing it today -- here is an excerpt from the logbook.

![image](https://user-images.githubusercontent.com/341037/57410381-e3647700-71a7-11e9-958d-150aed78c69d.png)

Looks like it happens when the car is unplugged.  There is a spurious(?) emission of pilot current value that I treat like someone purposely changed the setting.  I am not sure why this is happening yet but I'll look at it as soon as I can (which will probably be a day or two.)

**Comment by TonyApuzzo** [comment]
Just a bump -- I do still intend to work on this, just have had a bunch of other annoyances getting in the way.  I do experience the problem with the pilot charge current getting reset so just about every time I charge I am reminded of this issue, so I won't forget about it!

**Comment by DrFrankReade** [comment]
No problem, the work-around seems to be to disable the automation "Set OpenEVSE Charge Current"
![image](https://user-images.githubusercontent.com/10439664/57641386-bf1ee680-7569-11e9-8de6-0f28099fbec9.png)

This prevents the update from the slider, but thus far, I've experienced no unscheduled current changes, so the change appears to be coming via the route of the automation. At any rate, this is an acceptable side-effect for now. Perhaps this summer I'll implement throttling when air conditioning season kicks in, to prevent massive power draw during the worst hours of the day.  But at the moment, the enable/disable is good enough for me. 

Thanks for working on this Tony.

**Comment by TonyApuzzo** [comment]
I pushed a change that I hope will eliminate the spurious / spontaneous charge current changes.  I am using REST API for more functionality now instead of MQTT.  (I will move more away from MQTT when I have time since there is a single HTTP response that retrieves almost everything I want and is easier to maintain.)

**Comment by TonyApuzzo** [comment]
Ugh -- my "fix" seems to have actually made things worse.  At the moment I think the new flakyness is more due to the extreme unreliability of the REST server on the OpenEVSE rather than a bug in the automation.  I will go back to the drawing board to see if I can come up with a better approach.

Example:
```text
2019-05-19 12:21:42 INFO (MainThread) [homeassistant.components.automation] Executing Update OpenEVSE Current Setting
2019-05-19 12:21:42 INFO (MainThread) [homeassistant.helpers.script] Script Update OpenEVSE Current Setting: Running script
2019-05-19 12:21:42 INFO (MainThread) [homeassistant.helpers.script] Script Update OpenEVSE Current Setting: Executing step call service
2019-05-19 12:21:42 WARNING (MainThread) [custom_components.input_number] Invalid value: 34663392.0 (range 10.0 - 40.0)
```

No idea how the REST sensor in Home Assistant combined with the RAPI REST API can come up with this.

Some more research and lack of progress... it seems that when the input_number custom component is initialized it can be before the value that is being controlled and this can cause spurious changes as well, so I'm getting random changes caused by HASS restarting as well as from OpenEVSE flakyness.  Frustration -- but it seems that removing my custom input_number component might reduce the spurious changes somewhat -- probably not really a big deal since it's pretty unlikely that anyone really wants to switch between Level 1 and Level 2 charging on-the-fly.

**Comment by DrFrankReade** [comment]
Hey Tony,

I noticed some new exciting trouble on my end here - On the fly switching from ENABLED to SLEEP, and since my wife drives a horrible e-Golf with it's non-compliant implementation of J1772, I have to physically unplug and replug the car if the charger goes in to sleep mode at any time. So I just pulled the SWITCH entries out of Openevse.yaml and I'll just use it as a read-only interface. 

![image](https://user-images.githubusercontent.com/10439664/58124418-0a1ca780-7bc3-11e9-943c-f84b0b0d8d46.png)


I am in full agreement with you that the ESP8266 is at the edge of acceptable performance for the task. I've been suggesting a move to a Pi Zero W, but since I don't program well, I can only suggest. An ESP32 is nice too, but I think the move to the Pi would really open up a lot more possibilities (and libraries)

**Comment by TonyApuzzo** [comment]
Bummer, sorry to hear that.  I've been following along a bit on the OpenEVSE project's github and it does sound like they are working towards a more robust remote application.

I haven't been able to get a completely reliable configuration for myself either. I did basically the same as what you've done and set the current adjustment to be read-only.  I noticed on my end that the "eco divert" setting is what sometimes gets randomly flipped and that forces the unit into sleep mode.  I haven't noticed it going disabled spontaneously (yet).

I set up PlatformIO and as I have time (rare now in the summer) I will start playing around a bit with the WiFi firmware and see if I can figure out how to make the MQTT service more robust.  I think that MQTT at least in theory should have lower overhead than HTTP so it should reduce the load on the ESP8266 if I can add a few things to the MQTT to make it fully usable without any HTTP requests.  

With any luck the official Raspberry Pi WiFi module will be ready before then 🙄 

I have an RPi Zero W that isn't being used so I anticipate that I'll be trying out the new API ASAP.
