### ISSUE TITLE
still working

### ISSUE THREAD

**Issue by doppiaemme** [TonyApuzzo/home-assistant-config#3]
Hi tony, 
can I ask you if this project is still alive?
I have installed it to integrate my openEVSE on HA but some features show issues, not sure if due to latest change in HA.

**Comment by TonyApuzzo** [comment]
Yes it is kinda -- I haven't been doing much to keep it alive, but the package in this repository is still working with our OpenEVSE device.

I do have on my list to re-factor my custom components based on the new input_number / input_select functions, but I haven't been very motivates since they still work.

The OpenEVSE project is moving on to a different remote API model that requires a different microcontroller (I think maybe a Raspberry Pi Zero W, but I haven't been tracking.) so longer-term a re-write will be needed.

**Comment by TonyApuzzo** [comment]
I noticed that my sample configuration (secrets) was very out of date, I've upgrade that and re-tested the OpenEVSE package on my local environment and it is working OK.  Please see issue #4 for details.
