### ISSUE TITLE
Latest Upload of openevse.yaml Doesn't Work/Missing Config

### ISSUE THREAD

**Issue by sembeeuk** [TonyApuzzo/home-assistant-config#4]
Looks like the last upload of the openevse.yaml file doesn't work correctly. 
There are three failures with the build in Configuration Validation routine built in to HA. 

The first failure is the file is using automations old, which has been replaced with automations_old. Easily fixed. 

The second failure is that the sample secrets.yaml content at the top of the file is missing:

OPENEVSE_REST_GET_CURRENT_CAPACITY_RANGE: "openevse/rapi/in/$GC" 

Again easily fixed, by adding the line in and then finding the correct RAPI code required. 

However the third failure I cannot find the cause. The validation test fails with:

"expected a dictionary for dictionary value @ data['packages']['sensor']"

In my experience that error usually means a bad character, but I cannot find it. 
I did try removing various parts of the file to see whether I could pin down the line with the error, but I kept getting the same error referencing different parts of the file. I only got no errors when everything above the automations was removed, so the error is in that section somewhere, but I can't find it. 

Steps to reproduce. 
1. Add the packages definition to the HA configuration and reboot. 
2. Download the YAML file directly by right click on the RAW button on the page and save it to the packages directory.
3. Create the secrets file. 
4. Go in to Server controls and choose Check Configuration under Configuration Validation. Corrections as above. 

I used the built in File editor to modify the file. 
It looks like a good package, so thank you for the work you have put in.

**Comment by TonyApuzzo** [comment]
Hi,

Can you point me to documentation of the rename of `automation old`?  I am using the latest released version 2020.1.5 (not the beta) and my two word key is working.

The other problems you are experiencing I must apologize and say that it is because I have not kept the examples file up to date, I will check in a new version ASAP, probably this evening yet.

**Comment by sembeeuk** [comment]
I can't find it in the documentation, but I remember the change. 
The validation checker wih HA returns this:

"invalid slug automation old (try automation_old) for dictionary value @ data['packages']"

Making the change it suggests gets rid of the error.

**Comment by TonyApuzzo** [comment]
I think you may be loading the package incorrectly.  The error in question is not the result of the automation key being wrong.

Double-check your configuration.yaml to ensure that it is loading the packages folder thusly:
```yaml
homeassistant:
  # Load packages
  packages: !include_dir_named packages
```
I am using a feature called [labeled automation blocks](https://www.home-assistant.io/docs/automation/yaml/#yaml-example)

I updated the secrets_example.yaml and instead of using the word "old", which is confusing, I have changed the label to be "openevse" in the latest push.

This loads without error as-is in my configuration.

![image](https://user-images.githubusercontent.com/341037/106202190-cab7a400-6176-11eb-9356-e8ac192a4802.png)

**Comment by sembeeuk** [comment]
Thanks for the latest upload, and it is now working for me. It took me a few days to get a chance to test it. 

However I had to add in some additional bits which you might want to change the top of the openevse.yaml file to reflect to make it easier for others to use your component. 

The first is the requirement for the input_select custom component. I was getting an error on that and then found it elsewhere on this Github. Easily installed, but also missed as a requirement at the top of the file. 

The second is that some additional lines are required in secrets.yaml compared to what you have put in the sample list at the top of the file. Config checker kept failing, but with a bit of experimenting, I discovered they were:
`OPENEVSE_REST_GET_CURRENT_CAPACITY_RANGE: "http://192.168.x.x/r?json=1&rapi=$GC"
   OPENEVSE_REST_GET_CHARGING_CURRENT_AND_VOLTAGE: "http://192.168.x.x/r?json=1&rapi=$GG"
   OPENEVSE_REST_DISABLE: "http://192.168.x.x/r?json=1&rapi=$FD"
   OPENEVSE_REST_ENABLE: "http://192.168.x.x/r?json=1&rapi=$FE"  `

Where the IP address is the address of the OpenEVSE charger. I don't know if that was the correct way of doing it, but I found that worked. 

Finally, a very minor one this - one of your automations doesn't appear to have an alias and is coming up as "automation xx" (where xx is a number). It is the one with the ID "update_input_number_openevse_current". 

Its really good work.

**Comment by TonyApuzzo** [comment]
Thank you for your suggestions.

I have cleaned up the package with better documentation and fixed the automation id.  Instead of double-documentation of the required secrets, I referenced the `secrets-example.yaml` file where all the secrets are listed.
